In [1]:
import numpy as np

In [2]:
np.random.dirichlet((1, 1, 1), 10)

array([[0.54777259, 0.16453089, 0.28769653],
       [0.08194119, 0.90265635, 0.01540247],
       [0.45208571, 0.54531992, 0.00259437],
       [0.12969381, 0.30616615, 0.56414004],
       [0.78348779, 0.10470847, 0.11180374],
       [0.2500398 , 0.34189977, 0.40806043],
       [0.97137668, 0.00520808, 0.02341524],
       [0.43689598, 0.1563421 , 0.40676193],
       [0.48822489, 0.24069777, 0.27107734],
       [0.30370646, 0.32885587, 0.36743768]])

In [3]:
N = 3
x = np.random.uniform(0, 1, size=(N, N))

In [4]:
y = np.linalg.eig(x)

In [5]:
y.eigenvalues

array([ 1.72159257,  0.5570655 , -0.15424832])

In [6]:
y.eigenvectors

array([[-0.81198065, -0.70370912, -0.65458496],
       [-0.47945076,  0.70468928,  0.02446439],
       [-0.33288796, -0.0905897 ,  0.7555925 ]])

In [7]:
np.dot(y.eigenvectors, np.diag(y.eigenvalues))

array([[-1.39789985, -0.39201207,  0.10096863],
       [-0.82541887,  0.39255808, -0.00377359],
       [-0.57309744, -0.05046439, -0.11654887]])

In [8]:
x

array([[0.99172582, 0.55935217, 0.97466984],
       [0.350576  , 0.94163541, 0.26822877],
       [0.41220456, 0.36457876, 0.19104853]])

In [9]:
np.dot(x, y.eigenvectors)

array([[-1.39789985, -0.39201207,  0.10096863],
       [-0.82541887,  0.39255808, -0.00377359],
       [-0.57309744, -0.05046439, -0.11654887]])