In [1]:
import numpy as np

In [2]:
states = ['sunny', 'cloudy', 'rainy']

P = np.array([
    [0.7, 0.2, 0.1],
    [0.3, 0.4, 0.3],
    [0.2, 0.3, 0.5]
])

In [3]:
np.linalg.eig(P)

EigResult(eigenvalues=array([1.        , 0.47320508, 0.12679492]), eigenvectors=array([[-0.57735027, -0.61850691,  0.18695963],
       [-0.57735027,  0.34947835, -0.81216299],
       [-0.57735027,  0.70378554,  0.55266389]]))

In [12]:
from matplotlib.pyplot import axes


P = np.array([
    [3/4, 1/4, 0.0, 0.0],
    [1/2, 0.25, 0.25, 0.0],
    [0.25, 0.25, 0.25, 0.25],
    [0.0, 0.25, 0.25, 0.5]
])

Q = np.linalg.matrix_power(P, 3)
Q

array([[0.65625 , 0.25    , 0.078125, 0.015625],
       [0.578125, 0.25    , 0.109375, 0.0625  ],
       [0.453125, 0.25    , 0.15625 , 0.140625],
       [0.328125, 0.25    , 0.203125, 0.21875 ]])

In [16]:
np.linalg.matrix_power(P, 2)

array([[0.6875, 0.25  , 0.0625, 0.    ],
       [0.5625, 0.25  , 0.125 , 0.0625],
       [0.375 , 0.25  , 0.1875, 0.1875],
       [0.1875, 0.25  , 0.25  , 0.3125]])

In [15]:
Q.sum(axis=0)

array([2.015625, 1.      , 0.546875, 0.4375  ])

In [33]:
P = np.array([
    [0.5, 0.5, 0],
    [0.5, 0.5, 0],
    [0.25, 0.25, 0.5]
    
])

A = np.linalg.eig(P)

In [39]:
A.eigenvectors @ np.diag(A.eigenvalues ** 10000000) @ np.linalg.inv(A.eigenvectors)

array([[0.5, 0.5, 0. ],
       [0.5, 0.5, 0. ],
       [0.5, 0.5, 0. ]])

In [37]:
np.diag(A.eigenvalues ** 1)

array([[5.00000000e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.11022302e-16]])