In [1]:
import numpy as np
import torch

## Numpy

In [2]:
v = np.array([1, 40, 2, -3])

minval = np.min(v)
maxval = np.max(v)

minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min, Max : %g, %g' %(minval, maxval))

print('Min, Max indices : %g, %g' %(minidx, maxidx))

print(f'Min val is {v[minidx]} and Max val is {v[maxidx]}')

Min, Max : -3, 40
Min, Max indices : 3, 1
Min val is -3 and Max val is 40


In [3]:
M = np.array([[0, 1, 10], [20, 8, 5]])
print(M, '\n')


minvals1 = np.min(M)
minvals2 = np.min(M, axis=0)
minvals3 = np.min(M, axis=1)


print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]] 

0
[0 1 5]
[0 5]


In [4]:
minidx1 = np.argmin(M)
minidx2 = np.argmin(M, axis=0)
minidx3 = np.argmin(M, axis=1)


print(minidx1)
print(minidx2)
print(minidx3)

0
[0 0 1]
[0 2]


## Pytorch

In [5]:
v = torch.tensor([1, 40, 2, -3])

minval = torch.min(v)
maxval = torch.max(v)

print(f'Min, Max : {minval}, {maxval}')

minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print(f'Min, Max index : {minidx}, {maxidx}')
print(f'Min val is {v[minidx]} and Max val is {v[maxidx]}')

Min, Max : -3, 40
Min, Max index : 3, 1
Min val is -3 and Max val is 40


In [6]:
M = torch.tensor([[0, 1, 10], 
                  [20, 8, 5]])

print(M)

min1 = torch.min(M)
min2 = torch.min(M, axis = 0)
min3 = torch.min(M, axis = 1)

tensor([[ 0,  1, 10],
        [20,  8,  5]])


In [13]:
print(min1, '\n')
print(min2, '\n')
print(min3, '\n')

tensor(0) 

torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1])) 

torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 2])) 

